[package]
name = "hyper-json-server"
version = "0.1.0"
authors = ["Alexander Polyakov <plhk@sdf.org>"]

[dependencies]
hyper = "0.11"
tokio-proto = "0.1"
futures = "0.1"
error-chain = "0.11"
serde = "1.0"
serde_json = "1.0"
